spring:
  application:
    name: realestates
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: verde
    password: PASSWORD
    url: jdbc:mysql://localhost:3306/realestate
    name: verde
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  messages:
    basename: message

google:
  map:
    api:
      key: API_KEY

security:
  jwt:
    secret-key: a459654cc535e86c3e4879347aabd02f305b40982a02abfb228def3250d1ad5b
    expiration-time: 3600000