spring:
  application:
    name: realestates
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:verde
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
#spring:
#  application:
#    name: realestates
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: verde
#    password: PASSWORD
#    url: jdbc:mysql://localhost:3306/realestate
#    name: verde
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  messages:
#    basename: message

google:
  map:
    api:
      key: API_KEY

security:
  jwt:
    secret-key: a459654cc535e86c3e4879347aabd02f305b40982a02abfb228def3250d1ad5b
    expiration-time: 3600000